apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: react-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app 
    spec:
      containers:
      - name: react-app 
        image: core-harbor.f88.co/library/react-app:latest
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: ssl-certs
            mountPath: /etc/ssl/certs/
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
      imagePullSecrets:
      - name: harbor-cred
