apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: react-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app 
    spec:
      serviceAccountName: deployment-serviceaccount
      containers:
        - name: react-app 
          image: namdh1985/react-app:latest 
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: harbor-certs
              mountPath: /etc/ssl/certs
              subPath: ca.crt
      volumes:
        - name: harbor-certs
          configMap:
            name: harbor-certs
            namespace: kube-system   
      imagePullSecrets:
        - name: harbor-cred
